PRODUCT_COPY_FILES += \
    $(W7_VENDOR_DIR)/vendor/lib/lib-dplmedia.so:system/vendor/lib/lib-dplmedia.so \
    $(W7_VENDOR_DIR)/vendor/firmware/keymaster/keymaster.b00:system/vendor/firmware/keymaster/keymaster.b00 \
    $(W7_VENDOR_DIR)/vendor/firmware/keymaster/keymaster.b02:system/vendor/firmware/keymaster/keymaster.b02 \
    $(W7_VENDOR_DIR)/vendor/firmware/keymaster/keymaster.mdt:system/vendor/firmware/keymaster/keymaster.mdt \
    $(W7_VENDOR_DIR)/vendor/firmware/keymaster/keymaster.b01:system/vendor/firmware/keymaster/keymaster.b01 \
    $(W7_VENDOR_DIR)/vendor/firmware/keymaster/keymaster.b03:system/vendor/firmware/keymaster/keymaster.b03 \
    $(W7_VENDOR_DIR)/vendor/firmware/leia_pfp_470.fw:system/vendor/firmware/leia_pfp_470.fw \
    $(W7_VENDOR_DIR)/vendor/firmware/leia_pm4_470.fw:system/vendor/firmware/leia_pm4_470.fw \
    $(W7_VENDOR_DIR)/vendor/firmware/a225p5_pm4.fw:system/vendor/firmware/a225p5_pm4.fw \
    $(W7_VENDOR_DIR)/vendor/firmware/venus.b01:system/vendor/firmware/venus.b01 \
    $(W7_VENDOR_DIR)/vendor/firmware/venus.b03:system/vendor/firmware/venus.b03 \
    $(W7_VENDOR_DIR)/vendor/firmware/venus.mbn:system/vendor/firmware/venus.mbn \
    $(W7_VENDOR_DIR)/vendor/firmware/venus.b00:system/vendor/firmware/venus.b00 \
    $(W7_VENDOR_DIR)/vendor/firmware/venus.b02:system/vendor/firmware/venus.b02 \
    $(W7_VENDOR_DIR)/vendor/firmware/venus.b04:system/vendor/firmware/venus.b04 \
    $(W7_VENDOR_DIR)/vendor/firmware/venus.mdt:system/vendor/firmware/venus.mdt \
    $(W7_VENDOR_DIR)/vendor/firmware/a225_pm4.fw:system/vendor/firmware/a225_pm4.fw \
    $(W7_VENDOR_DIR)/vendor/firmware/a300_pm4.fw:system/vendor/firmware/a300_pm4.fw \
    $(W7_VENDOR_DIR)/vendor/firmware/a330_pm4.fw:system/vendor/firmware/a330_pm4.fw \
    $(W7_VENDOR_DIR)/vendor/firmware/a225_pfp.fw:system/vendor/firmware/a225_pfp.fw \
    $(W7_VENDOR_DIR)/vendor/firmware/a300_pfp.fw:system/vendor/firmware/a300_pfp.fw \
    $(W7_VENDOR_DIR)/vendor/firmware/a330_pfp.fw:system/vendor/firmware/a330_pfp.fw \
    $(W7_VENDOR_DIR)/vendor/firmware/cpp_firmware_v1_1_6.fw:system/vendor/firmware/cpp_firmware_v1_1_6.fw \
    $(W7_VENDOR_DIR)/vendor/firmware/cpp_firmware_v1_1_1.fw:system/vendor/firmware/cpp_firmware_v1_1_1.fw \
    $(W7_VENDOR_DIR)/vendor/firmware/cpp_firmware_v1_2_0.fw:system/vendor/firmware/cpp_firmware_v1_2_0.fw \
    $(W7_VENDOR_DIR)/lib/libchromatix_imx219_common.so:system/lib/libchromatix_imx219_common.so \
    $(W7_VENDOR_DIR)/lib/libchromatix_imx219_default_video.so:system/lib/libchromatix_imx219_default_video.so \
    $(W7_VENDOR_DIR)/lib/libchromatix_imx219_preview.so:system/lib/libchromatix_imx219_preview.so \
    $(W7_VENDOR_DIR)/lib/libchromatix_imx219_snapshot.so:system/lib/libchromatix_imx219_snapshot.so \
    $(W7_VENDOR_DIR)/lib/libmmcamera_imx219.so:system/lib/libmmcamera_imx219.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera_imx219_eeprom.so:system/vendor/lib/libmmcamera_imx219_eeprom.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera_mt9m114.so:system/vendor/lib/libmmcamera_mt9m114.so \
    $(W7_VENDOR_DIR)/etc/firmware/libpn547_fw.so:system/etc/firmware/libpn547_fw.so \
