PRODUCT_COPY_FILES +=\
	$(W7_VENDOR_DIR)/etc/gps.conf:system/etc/gps.conf \
	$(W7_VENDOR_DIR)/etc/media_codecs.xml:system/etc/media_codecs.xml \
	$(W7_VENDOR_DIR)/etc/sensor_def_qcomdev.conf:system/etc/sensor_def_qcomdev.conf \
	$(W7_VENDOR_DIR)/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pw4.fw \
	$(W7_VENDOR_DIR)/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
	$(W7_VENDOR_DIR)/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
	$(W7_VENDOR_DIR)/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
	$(W7_VENDOR_DIR)/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
	$(W7_VENDOR_DIR)/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
	$(W7_VENDOR_DIR)/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
	$(W7_VENDOR_DIR)/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
	$(W7_VENDOR_DIR)/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
	$(W7_VENDOR_DIR)/etc/firmware/cpp_firmware_v1_2_0.fw:syste/etc/firmware/cpp_firmware_v1_2_0.fw \
	$(W7_VENDOR_DIR)/etc/firmware/leia_pfp_470.fw:system/leia_pfp_470.fw \
	$(W7_VENDOR_DIR)/etc/firmware/leia_pm4_470.fw:system/etc/firmware/lei_pm4_470.fw \
	$(W7_VENDOR_DIR)/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
	$(W7_VENDOR_DIR)/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
	$(W7_VENDOR_DIR)/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
	$(W7_VENDOR_DIR)/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
	$(W7_VENDOR_DIR)/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
	$(W7_VENDOR_DIR)/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
	$(W7_VENDOR_DIR)/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
	$(W7_VENDOR_DIR)/etc/firmware/wcd9306/wcd9306_mbhc.bin:system/etc/firmware/wcd9306/wcd9306_mbhc.bin \
	$(W7_VENDOR_DIR)/etc/firmware/wcd9306/wcd9306_anc.bin:system/etc/firmware/wcd9306/wcd9306_anc.bin \
	$(W7_VENDOR_DIR)/lib/libA9BarcodeDecoder.so:system/lib/libA9barcodeDecoder.so \
	$(W7_VENDOR_DIR)/lib/liballjoyn.so:system/lib/liballjoyn.so \
	$(W7_VENDOR_DIR)/lib/libatd_common.so:system/lib/libatd_common.so \
	$(W7_VENDOR_DIR)/lib/libatd_corelib.so:system/lib/libatd_corelib.so \
	$(W7_VENDOR_DIR)/lib/libatd_modeminterface.so:system/lib/libatd_libmodeminterface.so \
	$(W7_VENDOR_DIR)/lib/libdrmframework.so:system/lib/libdrmframework.so \
	$(W7_VENDOR_DIR)/lib/libdrmframework_jni.so:system/lib/libdrmframework_jni.so \
	$(W7_VENDOR_DIR)/lib/libvss_dmi_qcci.so:system/lib/libvss_dmi_qcci.so \
	$(W7_VENDOR_DIR)/lib/libvss_gnss_qcci.so:system/lib/libvss_gnss_qcci.so \
	$(W7_VENDOR_DIR)/lib/libvss_ims_qcci.so:system/lib/libvss_ims_qcci.so \
	$(W7_VENDOR_DIR)/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
	$(W7_VENDOR_DIR)/vendor/lib/mediadrm/libwvdrmengine.so:system/lib/mediadrm/libwvdrmengine.so \
	$(W7_VENDOR_DIR)/vendor/lib/libc2d2_z180.so:system/vendor/lib/libc2d2_z180.so \
	$(W7_VENDOR_DIR)/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
	$(W7_VENDOR_DIR)/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
	$(W7_VENDOR_DIR)/vendor/lib/libdrmdiag.so:system/vendor/lib/libdrmdiag.so \
	$(W7_VENDOR_DIR)/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
	$(W7_VENDOR_DIR)/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
	$(W7_VENDOR_DIR)/vendor/lib/lib-imsqimf.so:system/vendor/lib/lib-imsqimf.so \
	$(W7_VENDOR_DIR)/vendor/lib/libmmQSM.so:system/vendor/lib/libmmQSM.so \
	$(W7_VENDOR_DIR)/vendor/lib/libmmQTA.so:system/vendor/lib/libmmQTA.so \
	$(W7_VENDOR_DIR)/vendor/lib/libnetxt_plugin_proxy.so:system/vendor/lib/libnetxt_plugin_proxy.so \
	$(W7_VENDOR_DIR)/vendor/lib/libnfc_ndef.so:system/vendor/lib/libnfc_ndef.so \
	$(W7_VENDOR_DIR)/vendor/lib/libNimsWrap.so:system/vendor/lib/libNimsWrap.so \
	$(W7_VENDOR_DIR)/vendor/lib/liboi_sbc_decoder.so:system/vendor/lib/liboi_sbc_decoder.so \
	$(W7_VENDOR_DIR)/vendor/lib/libpp_proc_plugin.so:system/vendor/lib/libpp_proc_plugin.so \
	$(W7_VENDOR_DIR)/vendor/lib/libprdrmdecrypt.so:system/vendor/lib/libprdrmdecrypt.so \
	$(W7_VENDOR_DIR)/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
	$(W7_VENDOR_DIR)/vendor/lib/libqmodem_plugin.so:system/vendor/lib/libqmodem_plugin.so \
	$(W7_VENDOR_DIR)/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
	$(W7_VENDOR_DIR)/vendor/lib/libsensor_test.so:system/vendor/lib/libsensor_test.so \
	$(W7_VENDOR_DIR)/vendor/lib/libsensor_user_cal.so:system/vendor/lib/libsensor_user_cal.so \
	$(W7_VENDOR_DIR)/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
	$(W7_VENDOR_DIR)/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwndrm_L3.so \
	$(W7_VENDOR_DIR)/vendor/lib/lib-dplmedia.so:system/vendor/lib/lib-dplmedia.so \
    $(W7_VENDOR_DIR)/app/TimeService.apk:system/app/TimeService.apk \
    $(W7_VENDOR_DIR)/bin/time_daemon:system/bin/time_daemon \
    $(W7_VENDOR_DIR)/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    $(W7_VENDOR_DIR)/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    $(W7_VENDOR_DIR)/etc/firmware/keymaster.b00:system/etc/firmware/keymaster.b00 \
    $(W7_VENDOR_DIR)/etc/firmware/keymaster.b02:system/etc/firmware/keymaster.b02 \
    $(W7_VENDOR_DIR)/etc/firmware/keymaster.mdt:system/etc/firmware/keymaster.mdt \
    $(W7_VENDOR_DIR)/etc/firmware/keymaster.b01:system/etc/firmware/keymaster.b01 \
    $(W7_VENDOR_DIR)/etc/firmware/keymaster.b03:system/etc/firmware/keymaster.b03 \
    $(W7_VENDOR_DIR)/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    $(W7_VENDOR_DIR)/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    $(W7_VENDOR_DIR)/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    $(W7_VENDOR_DIR)/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    $(W7_VENDOR_DIR)/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    $(W7_VENDOR_DIR)/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    $(W7_VENDOR_DIR)/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    $(W7_VENDOR_DIR)/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    $(W7_VENDOR_DIR)/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    $(W7_VENDOR_DIR)/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    $(W7_VENDOR_DIR)/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    $(W7_VENDOR_DIR)/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    $(W7_VENDOR_DIR)/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    $(W7_VENDOR_DIR)/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    $(W7_VENDOR_DIR)/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    $(W7_VENDOR_DIR)/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    $(W7_VENDOR_DIR)/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    $(W7_VENDOR_DIR)/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    $(W7_VENDOR_DIR)/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    $(W7_VENDOR_DIR)/etc/media_profiles.xml:system/etc/media_profiles.xml \
