# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/w7/setup-makefiles.sh

#lines addeed by demonslayer12349 to allow certain blobs to be used on d415 variant builds
ifeq ($(TARGET_W7_VARIANT), )
TARGET_W7_VARIANT := D415
endif

ifeq ($(TARGET_W7_VARIANT),D415)
W7_VENDOR_DIR := vendor/lge/w7/D415-proprietary
include vendor/lge/w7/D415-extras.mk
else
W7_VENDOR_DIR := vendor/lge/w7/proprietary
include vendor/lge/w7/D410x-extras.mk
endif
PRODUCT_COPY_FILES += \
	    $(W7_VENDOR_DIR)/vendor/lib/libtime_genoff.so:obj/lib/libtime_genoff.so \
    $(W7_VENDOR_DIR)/etc/ACDB/Bluetooth_cal.acdb:system/etc/ACDB/Bluetooth_cal.acdb \
    $(W7_VENDOR_DIR)/etc/ACDB/General_cal.acdb:system/etc/ACDB/General_cal.acdb \
    $(W7_VENDOR_DIR)/etc/ACDB/Global_cal.acdb:system/etc/ACDB/Global_cal.acdb \
    $(W7_VENDOR_DIR)/etc/ACDB/Handset_cal.acdb:system/etc/ACDB/Handset_cal.acdb \
    $(W7_VENDOR_DIR)/etc/ACDB/Hdmi_cal.acdb:system/etc/ACDB/Hdmi_cal.acdb \
    $(W7_VENDOR_DIR)/etc/ACDB/Headset_cal.acdb:system/etc/ACDB/Headset_cal.acdb \
    $(W7_VENDOR_DIR)/etc/ACDB/Speaker_cal.acdb:system/etc/ACDB/Speaker_cal.acdb \
    $(W7_VENDOR_DIR)/etc/ACDB/workspaceFile.qwsp:system/etc/ACDB/workspaceFile.qwsp \
    $(W7_VENDOR_DIR)/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    $(W7_VENDOR_DIR)/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    $(W7_VENDOR_DIR)/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    $(W7_VENDOR_DIR)/vendor/lib/libaudioalsa.so:system/vendor/lib/libaudioalsa.so \
    $(W7_VENDOR_DIR)/vendor/lib/libacdbmapper.so:system/vendor/lib/libacdbmapper.so \
    $(W7_VENDOR_DIR)/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    $(W7_VENDOR_DIR)/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    $(W7_VENDOR_DIR)/lib/libtinycompress.so:system/lib/libtinycompress.so \
    $(W7_VENDOR_DIR)/lib/hw/audio.primary.msm8226.so:system/lib/hw/audio.primary.msm8226.so \
    $(W7_VENDOR_DIR)/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
    $(W7_VENDOR_DIR)/vendor/lib/liblistenhardware.so:system/vendor/lib/liblistenhardware.so \
    $(W7_VENDOR_DIR)/vendor/lib/liblistenjni.so:system/vendor/lib/liblistenjni.so \
    $(W7_VENDOR_DIR)/vendor/lib/liblisten.so:system/vendor/lib/liblisten.so \
    $(W7_VENDOR_DIR)/vendor/lib/liblistensoundmodel.so:system/vendor/lib/liblistensoundmodel.so \
    $(W7_VENDOR_DIR)/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    $(W7_VENDOR_DIR)/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    $(W7_VENDOR_DIR)/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    $(W7_VENDOR_DIR)/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    $(W7_VENDOR_DIR)/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    $(W7_VENDOR_DIR)/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    $(W7_VENDOR_DIR)/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    $(W7_VENDOR_DIR)/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    $(W7_VENDOR_DIR)/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    $(W7_VENDOR_DIR)/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    $(W7_VENDOR_DIR)/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    $(W7_VENDOR_DIR)/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    $(W7_VENDOR_DIR)/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    $(W7_VENDOR_DIR)/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    $(W7_VENDOR_DIR)/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    $(W7_VENDOR_DIR)/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    $(W7_VENDOR_DIR)/vendor/lib/libdsnetutils.so:system/vendor/lib/libdsnetutils.so \
    $(W7_VENDOR_DIR)/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    $(W7_VENDOR_DIR)/lib/libvss_common_iface.so:system/lib/libvss_common_iface.so \
    $(W7_VENDOR_DIR)/lib/libvss_common_idl.so:system/lib/libvss_common_idl.so \
    $(W7_VENDOR_DIR)/lib/libvss_nv_iface.so:system/lib/libvss_nv_iface.so \
    $(W7_VENDOR_DIR)/lib/libvss_nv_idl.so:system/lib/libvss_nv_idl.so \
    $(W7_VENDOR_DIR)/lib/libvss_common_core.so:system/lib/libvss_common_core.so \
    $(W7_VENDOR_DIR)/lib/libvss_nv_core.so:system/lib/libvss_nv_core.so \
    $(W7_VENDOR_DIR)/lib/libril.so:system/lib/libril.so \
    $(W7_VENDOR_DIR)/bin/qmuxd:system/bin/qmuxd \
    $(W7_VENDOR_DIR)/bin/rild:system/bin/rild \
    $(W7_VENDOR_DIR)/bin/rmt_storage:system/bin/rmt_storage \
    $(W7_VENDOR_DIR)/bin/netmgrd:system/bin/netmgrd \
    $(W7_VENDOR_DIR)/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    $(W7_VENDOR_DIR)/vendor/lib/libdsucsd.so:system/vendor/lib/libdsucsd.so \
    $(W7_VENDOR_DIR)/vendor/lib/libqmi_csvt_srvc.so:system/vendor/lib/libqmi_csvt_srvc.so \
    $(W7_VENDOR_DIR)/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    $(W7_VENDOR_DIR)/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    $(W7_VENDOR_DIR)/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    $(W7_VENDOR_DIR)/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    $(W7_VENDOR_DIR)/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    $(W7_VENDOR_DIR)/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    $(W7_VENDOR_DIR)/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    $(W7_VENDOR_DIR)/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    $(W7_VENDOR_DIR)/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    $(W7_VENDOR_DIR)/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    $(W7_VENDOR_DIR)/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    $(W7_VENDOR_DIR)/vendor/lib/libc2d30.so:system/vendor/lib/libc2d30.so \
    $(W7_VENDOR_DIR)/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    $(W7_VENDOR_DIR)/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    $(W7_VENDOR_DIR)/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    $(W7_VENDOR_DIR)/vendor/lib/libOpenVG.so:system/vendor/lib/libOpenVG.so \
    $(W7_VENDOR_DIR)/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    $(W7_VENDOR_DIR)/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    $(W7_VENDOR_DIR)/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    $(W7_VENDOR_DIR)/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    $(W7_VENDOR_DIR)/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    $(W7_VENDOR_DIR)/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    $(W7_VENDOR_DIR)/lib/hw/camera.msm8226.so:system/lib/hw/camera.msm8226.so \
    $(W7_VENDOR_DIR)/lib/libchromatix_hi543_common.so:system/lib/libchromatix_hi543_common.so \
    $(W7_VENDOR_DIR)/lib/libchromatix_hi543_default_video.so:system/lib/libchromatix_hi543_default_video.so \
    $(W7_VENDOR_DIR)/lib/libchromatix_hi543_preview.so:system/lib/libchromatix_hi543_preview.so \
    $(W7_VENDOR_DIR)/lib/libchromatix_hi543_snapshot.so:system/lib/libchromatix_hi543_snapshot.so \
    $(W7_VENDOR_DIR)/lib/libchromatix_imx111_common.so:system/lib/libchromatix_imx111_common.so \
    $(W7_VENDOR_DIR)/lib/libchromatix_imx111_default_video.so:system/lib/libchromatix_imx111_default_video.so \
    $(W7_VENDOR_DIR)/lib/libchromatix_imx111_preview.so:system/lib/libchromatix_imx111_preview.so \
    $(W7_VENDOR_DIR)/lib/libchromatix_imx111_snapshot.so:system/lib/libchromatix_imx111_snapshot.so \
    $(W7_VENDOR_DIR)/lib/libchromatix_imx119_common.so:system/lib/libchromatix_imx119_common.so \
    $(W7_VENDOR_DIR)/lib/libchromatix_imx119_default_video.so:system/lib/libchromatix_imx119_default_video.so \
    $(W7_VENDOR_DIR)/lib/libchromatix_imx119_preview.so:system/lib/libchromatix_imx119_preview.so \
    $(W7_VENDOR_DIR)/lib/libchromatix_imx179_common.so:system/lib/libchromatix_imx179_common.so \
    $(W7_VENDOR_DIR)/lib/libchromatix_imx179_default_video.so:system/lib/libchromatix_imx179_default_video.so \
    $(W7_VENDOR_DIR)/lib/libchromatix_imx179_preview.so:system/lib/libchromatix_imx179_preview.so \
    $(W7_VENDOR_DIR)/lib/libchromatix_imx179_snapshot.so:system/lib/libchromatix_imx179_snapshot.so \
    $(W7_VENDOR_DIR)/lib/libmmcamera_hi707.so:system/lib/libmmcamera_hi707.so \
    $(W7_VENDOR_DIR)/lib/libmmcamera_hi543.so:system/lib/libmmcamera_hi543.so \
    $(W7_VENDOR_DIR)/lib/libmmcamera_imx111.so:system/lib/libmmcamera_imx111.so \
    $(W7_VENDOR_DIR)/lib/libmmcamera_imx119.so:system/lib/libmmcamera_imx119.so \
    $(W7_VENDOR_DIR)/lib/libmmcamera_imx179.so:system/lib/libmmcamera_imx179.so \
    $(W7_VENDOR_DIR)/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    $(W7_VENDOR_DIR)/lib/libmorpho_image_stab31.so:system/lib/libmorpho_image_stab31.so \
    $(W7_VENDOR_DIR)/lib/libmorpho_memory_allocator.so:system/lib/libmorpho_memory_allocator.so \
    $(W7_VENDOR_DIR)/lib/libmorpho_panorama_gp.so:system/lib/libmorpho_panorama_gp.so \
    $(W7_VENDOR_DIR)/lib/libmorpho_panorama_wa_viewer.so:system/lib/libmorpho_panorama_wa_viewer.so \
    $(W7_VENDOR_DIR)/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    $(W7_VENDOR_DIR)/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
    $(W7_VENDOR_DIR)/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera_hi351.so:system/vendor/lib/libmmcamera_hi351.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera_hi543_eeprom.so:system/vendor/lib/libmmcamera_hi543_eeprom.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera_imx111_eeprom.so:system/vendor/lib/libmmcamera_imx111_eeprom.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera_imx179_eeprom.so:system/vendor/lib/libmmcamera_imx179_eeprom.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    $(W7_VENDOR_DIR)/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    $(W7_VENDOR_DIR)/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    $(W7_VENDOR_DIR)/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    $(W7_VENDOR_DIR)/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmm-hdcpmgr.so:system/vendor/lib/libmm-hdcpmgr.so \
    $(W7_VENDOR_DIR)/lib/libqomx_core.so:system/lib/libqomx_core.so \
    $(W7_VENDOR_DIR)/lib/libdashplayer.so:system/lib/libdashplayer.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmmipstreamaal.so:system/vendor/lib/libmmipstreamaal.so \
    $(W7_VENDOR_DIR)/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    $(W7_VENDOR_DIR)/vendor/lib/libOmxAmrwbplusDec.so:system/vendor/lib/libOmxAmrwbplusDec.so \
    $(W7_VENDOR_DIR)/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    $(W7_VENDOR_DIR)/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    $(W7_VENDOR_DIR)/vendor/lib/libOmxWmaDec.so:system/vendor/lib/libOmxWmaDec.so \
    $(W7_VENDOR_DIR)/bin/adsprpcd:system/bin/adsprpcd \
    $(W7_VENDOR_DIR)/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    $(W7_VENDOR_DIR)/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    $(W7_VENDOR_DIR)/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so \
    $(W7_VENDOR_DIR)/vendor/lib/rfsa/adsp/libadsp_denoise_skel.so:system/vendor/lib/rfsa/adsp/libadsp_denoise_skel.so \
    $(W7_VENDOR_DIR)/vendor/lib/rfsa/adsp/libdspCV_skel.so:system/vendor/lib/rfsa/adsp/libdspCV_skel.so \
    $(W7_VENDOR_DIR)/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so:system/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so \
    $(W7_VENDOR_DIR)/vendor/lib/rfsa/adsp/libfastcvadsp.so:system/vendor/lib/rfsa/adsp/libfastcvadsp.so \
    $(W7_VENDOR_DIR)/bin/thermal-engine:system/bin/thermal-engine \
    $(W7_VENDOR_DIR)/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
    $(W7_VENDOR_DIR)/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    $(W7_VENDOR_DIR)/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    $(W7_VENDOR_DIR)/lib/libloc_core.so:system/lib/libloc_core.so \
    $(W7_VENDOR_DIR)/lib/libloc_eng.so:system/lib/libloc_eng.so \
    $(W7_VENDOR_DIR)/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    $(W7_VENDOR_DIR)/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    $(W7_VENDOR_DIR)/lib/libgps.utils.so:system/lib/libgps.utils.so \
    $(W7_VENDOR_DIR)/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    $(W7_VENDOR_DIR)/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    $(W7_VENDOR_DIR)/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
    $(W7_VENDOR_DIR)/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    $(W7_VENDOR_DIR)/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    $(W7_VENDOR_DIR)/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    $(W7_VENDOR_DIR)/vendor/lib/hw/sensors.msm8226.so:system/vendor/lib/hw/sensors.msm8226.so \
    $(W7_VENDOR_DIR)/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    $(W7_VENDOR_DIR)/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    $(W7_VENDOR_DIR)/bin/sensors.qcom:system/bin/sensors.qcom \
    $(W7_VENDOR_DIR)/lib/hw/lights.msm8226.so:system/lib/hw/lights.msm8226.so \
    $(W7_VENDOR_DIR)/vendor/lib/libbmc050.so:system/vendor/lib/libbmc050.so \
    $(W7_VENDOR_DIR)/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    $(W7_VENDOR_DIR)/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    $(W7_VENDOR_DIR)/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
    $(W7_VENDOR_DIR)/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
    $(W7_VENDOR_DIR)/bin/ims_rtp_daemon:system/bin/ims_rtp_daemon \
    $(W7_VENDOR_DIR)/vendor/lib/lib-imsdpl.so:system/vendor/lib/lib-imsdpl.so \
    $(W7_VENDOR_DIR)/vendor/lib/lib-rtpsl.so:system/vendor/lib/lib-rtpsl.so \
    $(W7_VENDOR_DIR)/vendor/lib/lib-rtpcore.so:system/vendor/lib/lib-rtpcore.so \
    $(W7_VENDOR_DIR)/vendor/lib/lib-rtpdaemoninterface.so:system/vendor/lib/lib-rtpdaemoninterface.so \
    $(W7_VENDOR_DIR)/vendor/lib/lib-rtpcommon.so:system/vendor/lib/lib-rtpcommon.so \
    $(W7_VENDOR_DIR)/bin/irrcServer:system/bin/irrcServer \
    $(W7_VENDOR_DIR)/lib/libirrc.so:system/lib/libirrc.so \
    $(W7_VENDOR_DIR)/lib/libirrcClient.so:system/lib/libirrcClient.so \
    $(W7_VENDOR_DIR)/lib/libirrcJni.so:system/lib/libirrcJni.so \
    $(W7_VENDOR_DIR)/lib/liblgewg.so:system/lib/liblgewg.so \
